version: '3.1'
services: 
  mongo: 
    image: mongo:latest
    restart: always
    volumes: 
      - ./database-data:/data/db
    ports: 
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example